import { Problem, DataStructure } from '../types'

const generateProblems = (): Problem[] => [
  // ARRAYS - 38 problems
  {
    id: 'arr_1',
    dataStructure: 'Arrays',
    name: 'Two Sum',
    link: 'https://leetcode.com/problems/two-sum/',
    pattern: 'Hashing',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'arr_2',
    dataStructure: 'Arrays',
    name: 'Best Time to Buy and Sell Stock',
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    pattern: 'Greedy',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'arr_3',
    dataStructure: 'Arrays',
    name: 'Contains Duplicate',
    link: 'https://leetcode.com/problems/contains-duplicate/',
    pattern: 'Hashing',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'arr_4',
    dataStructure: 'Arrays',
    name: 'Valid Palindrome',
    link: 'https://leetcode.com/problems/valid-palindrome/',
    pattern: 'Two Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'arr_5',
    dataStructure: 'Arrays',
    name: 'Product of Array Except Self',
    link: 'https://leetcode.com/problems/product-of-array-except-self/',
    pattern: 'Prefix Sum',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_6',
    dataStructure: 'Arrays',
    name: '3Sum',
    link: 'https://leetcode.com/problems/3sum/',
    pattern: 'Two Pointer',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_7',
    dataStructure: 'Arrays',
    name: 'Container With Most Water',
    link: 'https://leetcode.com/problems/container-with-most-water/',
    pattern: 'Two Pointer',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_8',
    dataStructure: 'Arrays',
    name: 'Maximum Subarray',
    link: 'https://leetcode.com/problems/maximum-subarray/',
    pattern: 'Kadane',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_9',
    dataStructure: 'Arrays',
    name: 'Sliding Window Maximum',
    link: 'https://leetcode.com/problems/sliding-window-maximum/',
    pattern: 'Sliding Window',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_10',
    dataStructure: 'Arrays',
    name: 'Trapping Rain Water',
    link: 'https://leetcode.com/problems/trapping-rain-water/',
    pattern: 'Two Pointer',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_11',
    dataStructure: 'Arrays',
    name: 'Merge Intervals',
    link: 'https://leetcode.com/problems/merge-intervals/',
    pattern: 'Intervals',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_12',
    dataStructure: 'Arrays',
    name: 'Search in Rotated Sorted Array',
    link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    pattern: 'Binary Search',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_13',
    dataStructure: 'Arrays',
    name: 'Find First and Last Position',
    link: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
    pattern: 'Binary Search',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_14',
    dataStructure: 'Arrays',
    name: 'Median of Two Sorted Arrays',
    link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    pattern: 'Binary Search',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_15',
    dataStructure: 'Arrays',
    name: 'Next Permutation',
    link: 'https://leetcode.com/problems/next-permutation/',
    pattern: 'Traversal',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_16',
    dataStructure: 'Arrays',
    name: 'Remove Duplicates from Sorted Array',
    link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
    pattern: 'Two Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'arr_17',
    dataStructure: 'Arrays',
    name: 'Rotate Array',
    link: 'https://leetcode.com/problems/rotate-array/',
    pattern: 'Array Manipulation',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_18',
    dataStructure: 'Arrays',
    name: 'Majority Element',
    link: 'https://leetcode.com/problems/majority-element/',
    pattern: 'Hashing',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'arr_19',
    dataStructure: 'Arrays',
    name: 'Longest Consecutive',
    link: 'https://leetcode.com/problems/longest-consecutive/',
    pattern: 'Hashing',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_20',
    dataStructure: 'Arrays',
    name: 'Set Matrix Zeroes',
    link: 'https://leetcode.com/problems/set-matrix-zeroes/',
    pattern: 'Matrix',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_21',
    dataStructure: 'Arrays',
    name: 'Spiral Matrix',
    link: 'https://leetcode.com/problems/spiral-matrix/',
    pattern: 'Matrix',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_22',
    dataStructure: 'Arrays',
    name: 'Rotate Matrix',
    link: 'https://leetcode.com/problems/rotate-image/',
    pattern: 'Matrix',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_23',
    dataStructure: 'Arrays',
    name: 'Search a 2D Matrix',
    link: 'https://leetcode.com/problems/search-a-2d-matrix/',
    pattern: 'Binary Search',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_24',
    dataStructure: 'Arrays',
    name: 'Permutations',
    link: 'https://leetcode.com/problems/permutations/',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_25',
    dataStructure: 'Arrays',
    name: 'Subsets',
    link: 'https://leetcode.com/problems/subsets/',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_26',
    dataStructure: 'Arrays',
    name: 'Combination Sum',
    link: 'https://leetcode.com/problems/combination-sum/',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_27',
    dataStructure: 'Arrays',
    name: 'Letter Combinations',
    link: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_28',
    dataStructure: 'Arrays',
    name: 'Word Search',
    link: 'https://leetcode.com/problems/word-search/',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_29',
    dataStructure: 'Arrays',
    name: 'N-Queens',
    link: 'https://leetcode.com/problems/n-queens/',
    pattern: 'Backtracking',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_30',
    dataStructure: 'Arrays',
    name: 'Minimum Window Substring',
    link: 'https://leetcode.com/problems/minimum-window-substring/',
    pattern: 'Sliding Window',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_31',
    dataStructure: 'Arrays',
    name: 'Subarray Sum Equals K',
    link: 'https://leetcode.com/problems/subarray-sum-equals-k/',
    pattern: 'Prefix Sum',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_32',
    dataStructure: 'Arrays',
    name: 'Gas Station',
    link: 'https://leetcode.com/problems/gas-station/',
    pattern: 'Greedy',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_33',
    dataStructure: 'Arrays',
    name: 'Candy',
    link: 'https://leetcode.com/problems/candy/',
    pattern: 'Greedy',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_34',
    dataStructure: 'Arrays',
    name: 'Maximum Product Subarray',
    link: 'https://leetcode.com/problems/maximum-product-subarray/',
    pattern: 'DP',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_35',
    dataStructure: 'Arrays',
    name: 'First Missing Positive',
    link: 'https://leetcode.com/problems/first-missing-positive/',
    pattern: 'Array Manipulation',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'arr_36',
    dataStructure: 'Arrays',
    name: 'Longest Substring Without Repeating Characters',
    link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    pattern: 'Sliding Window',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_37',
    dataStructure: 'Arrays',
    name: 'Jump Game',
    link: 'https://leetcode.com/problems/jump-game/',
    pattern: 'Greedy',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'arr_38',
    dataStructure: 'Arrays',
    name: 'Jump Game II',
    link: 'https://leetcode.com/problems/jump-game-ii/',
    pattern: 'Greedy',
    difficulty: 'Medium',
    completed: false,
  },

  // STRINGS - 28 problems
  {
    id: 'str_1',
    dataStructure: 'Strings',
    name: 'Valid Anagram',
    link: 'https://leetcode.com/problems/valid-anagram/',
    pattern: 'Frequency Counting',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_2',
    dataStructure: 'Strings',
    name: 'Isomorphic Strings',
    link: 'https://leetcode.com/problems/isomorphic-strings/',
    pattern: 'Hash Map',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_3',
    dataStructure: 'Strings',
    name: 'Valid Parentheses',
    link: 'https://leetcode.com/problems/valid-parentheses/',
    pattern: 'Stack',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_4',
    dataStructure: 'Strings',
    name: 'Reverse String',
    link: 'https://leetcode.com/problems/reverse-string/',
    pattern: 'Two Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_5',
    dataStructure: 'Strings',
    name: 'Palindrome Check',
    link: 'https://leetcode.com/problems/valid-palindrome-ii/',
    pattern: 'Palindrome',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_6',
    dataStructure: 'Strings',
    name: 'Longest Palindromic Substring',
    link: 'https://leetcode.com/problems/longest-palindromic-substring/',
    pattern: 'Palindrome',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_7',
    dataStructure: 'Strings',
    name: 'Implement strStr()',
    link: 'https://leetcode.com/problems/implement-strstr/',
    pattern: 'KMP',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_8',
    dataStructure: 'Strings',
    name: 'Longest Common Prefix',
    link: 'https://leetcode.com/problems/longest-common-prefix/',
    pattern: 'String Matching',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_9',
    dataStructure: 'Strings',
    name: 'Group Anagrams',
    link: 'https://leetcode.com/problems/group-anagrams/',
    pattern: 'Hash Map',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_10',
    dataStructure: 'Strings',
    name: 'Valid Parentheses String',
    link: 'https://leetcode.com/problems/valid-parenthesis-string/',
    pattern: 'Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_11',
    dataStructure: 'Strings',
    name: 'Decode String',
    link: 'https://leetcode.com/problems/decode-string/',
    pattern: 'Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_12',
    dataStructure: 'Strings',
    name: 'Word Pattern',
    link: 'https://leetcode.com/problems/word-pattern/',
    pattern: 'Hash Map',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_13',
    dataStructure: 'Strings',
    name: 'Integer to Roman',
    link: 'https://leetcode.com/problems/integer-to-roman/',
    pattern: 'Hash Map',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_14',
    dataStructure: 'Strings',
    name: 'Roman to Integer',
    link: 'https://leetcode.com/problems/roman-to-integer/',
    pattern: 'Hash Map',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_15',
    dataStructure: 'Strings',
    name: 'Atoi',
    link: 'https://leetcode.com/problems/string-to-integer-atoi/',
    pattern: 'Frequency Counting',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_16',
    dataStructure: 'Strings',
    name: 'Multiply Strings',
    link: 'https://leetcode.com/problems/multiply-strings/',
    pattern: 'String Matching',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_17',
    dataStructure: 'Strings',
    name: 'Add Strings',
    link: 'https://leetcode.com/problems/add-strings/',
    pattern: 'String Matching',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_18',
    dataStructure: 'Strings',
    name: 'Regular Expression Matching',
    link: 'https://leetcode.com/problems/regular-expression-matching/',
    pattern: 'DP',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'str_19',
    dataStructure: 'Strings',
    name: 'Wildcard Matching',
    link: 'https://leetcode.com/problems/wildcard-matching/',
    pattern: 'DP',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'str_20',
    dataStructure: 'Strings',
    name: 'Count and Say',
    link: 'https://leetcode.com/problems/count-and-say/',
    pattern: 'String Matching',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_21',
    dataStructure: 'Strings',
    name: 'Rotate String',
    link: 'https://leetcode.com/problems/rotate-string/',
    pattern: 'String Matching',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_22',
    dataStructure: 'Strings',
    name: 'Zigzag Conversion',
    link: 'https://leetcode.com/problems/zigzag-conversion/',
    pattern: 'String Matching',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_23',
    dataStructure: 'Strings',
    name: 'Minimum Window Substring',
    link: 'https://leetcode.com/problems/minimum-window-substring/',
    pattern: 'Sliding Window',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'str_24',
    dataStructure: 'Strings',
    name: 'Substring with Concatenation of All Words',
    link: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/',
    pattern: 'Sliding Window',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'str_25',
    dataStructure: 'Strings',
    name: 'First Unique Character',
    link: 'https://leetcode.com/problems/first-unique-character-in-a-string/',
    pattern: 'Frequency Counting',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'str_26',
    dataStructure: 'Strings',
    name: 'Can Shift Characters',
    link: 'https://leetcode.com/problems/can-you-make-a-string-equal-to-another-string/',
    pattern: 'Frequency Counting',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_27',
    dataStructure: 'Strings',
    name: 'Permutation in String',
    link: 'https://leetcode.com/problems/permutation-in-string/',
    pattern: 'Sliding Window',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'str_28',
    dataStructure: 'Strings',
    name: 'Split Concatenated Strings',
    link: 'https://leetcode.com/problems/split-concatenated-strings/',
    pattern: 'Sliding Window',
    difficulty: 'Medium',
    completed: false,
  },

  // LINKED LIST - 20 problems
  {
    id: 'll_1',
    dataStructure: 'Linked List',
    name: 'Reverse Linked List',
    link: 'https://leetcode.com/problems/reverse-linked-list/',
    pattern: 'Reversal',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_2',
    dataStructure: 'Linked List',
    name: 'Linked List Cycle Detection',
    link: 'https://leetcode.com/problems/linked-list-cycle/',
    pattern: 'Fast & Slow Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_3',
    dataStructure: 'Linked List',
    name: 'Find Cycle Start',
    link: 'https://leetcode.com/problems/linked-list-cycle-ii/',
    pattern: 'Cycle Detection',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_4',
    dataStructure: 'Linked List',
    name: 'Merge Two Sorted Lists',
    link: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    pattern: 'Merge',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_5',
    dataStructure: 'Linked List',
    name: 'Merge K Sorted Lists',
    link: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    pattern: 'Merge',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'll_6',
    dataStructure: 'Linked List',
    name: 'Remove Nth Node From End',
    link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
    pattern: 'Dummy Node',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_7',
    dataStructure: 'Linked List',
    name: 'Middle of Linked List',
    link: 'https://leetcode.com/problems/middle-of-the-linked-list/',
    pattern: 'Fast & Slow Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_8',
    dataStructure: 'Linked List',
    name: 'Palindrome Linked List',
    link: 'https://leetcode.com/problems/palindrome-linked-list/',
    pattern: 'Fast & Slow Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_9',
    dataStructure: 'Linked List',
    name: 'Reorder List',
    link: 'https://leetcode.com/problems/reorder-list/',
    pattern: 'Reversal',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_10',
    dataStructure: 'Linked List',
    name: 'Reverse Nodes in K Group',
    link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
    pattern: 'Reversal',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'll_11',
    dataStructure: 'Linked List',
    name: 'Intersection of Two Linked Lists',
    link: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
    pattern: 'Two Pointer',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_12',
    dataStructure: 'Linked List',
    name: 'Add Two Numbers',
    link: 'https://leetcode.com/problems/add-two-numbers/',
    pattern: 'Traversal',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_13',
    dataStructure: 'Linked List',
    name: 'Add Two Numbers II',
    link: 'https://leetcode.com/problems/add-two-numbers-ii/',
    pattern: 'Reversal',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_14',
    dataStructure: 'Linked List',
    name: 'Flatten Multilevel Doubly Linked List',
    link: 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/',
    pattern: 'Traversal',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_15',
    dataStructure: 'Linked List',
    name: 'LRU Cache',
    link: 'https://leetcode.com/problems/lru-cache/',
    pattern: 'LRU concepts',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_16',
    dataStructure: 'Linked List',
    name: 'Copy List with Random Pointer',
    link: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
    pattern: 'Hash Map',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_17',
    dataStructure: 'Linked List',
    name: 'Sort List',
    link: 'https://leetcode.com/problems/sort-list/',
    pattern: 'Merge Sort',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_18',
    dataStructure: 'Linked List',
    name: 'Partition List',
    link: 'https://leetcode.com/problems/partition-list/',
    pattern: 'Dummy Node',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'll_19',
    dataStructure: 'Linked List',
    name: 'Remove Duplicates from Sorted List',
    link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/',
    pattern: 'Traversal',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'll_20',
    dataStructure: 'Linked List',
    name: 'Swapping Nodes in Pairs',
    link: 'https://leetcode.com/problems/swap-nodes-in-pairs/',
    pattern: 'Dummy Node',
    difficulty: 'Medium',
    completed: false,
  },

  // STACK - 20 problems
  {
    id: 'stk_1',
    dataStructure: 'Stack',
    name: 'Valid Parentheses',
    link: 'https://leetcode.com/problems/valid-parentheses/',
    pattern: 'Parentheses',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'stk_2',
    dataStructure: 'Stack',
    name: 'Min Stack',
    link: 'https://leetcode.com/problems/min-stack/',
    pattern: 'Min Stack',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'stk_3',
    dataStructure: 'Stack',
    name: 'Next Greater Element I',
    link: 'https://leetcode.com/problems/next-greater-element-i/',
    pattern: 'Monotonic Stack',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'stk_4',
    dataStructure: 'Stack',
    name: 'Next Greater Element II',
    link: 'https://leetcode.com/problems/next-greater-element-ii/',
    pattern: 'Monotonic Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_5',
    dataStructure: 'Stack',
    name: 'Daily Temperatures',
    link: 'https://leetcode.com/problems/daily-temperatures/',
    pattern: 'Monotonic Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_6',
    dataStructure: 'Stack',
    name: 'Largest Rectangle in Histogram',
    link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    pattern: 'Histogram',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'stk_7',
    dataStructure: 'Stack',
    name: 'Maximal Rectangle',
    link: 'https://leetcode.com/problems/maximal-rectangle/',
    pattern: 'Histogram',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'stk_8',
    dataStructure: 'Stack',
    name: 'Evaluate Reverse Polish Notation',
    link: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
    pattern: 'Expression Evaluation',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_9',
    dataStructure: 'Stack',
    name: 'Basic Calculator',
    link: 'https://leetcode.com/problems/basic-calculator/',
    pattern: 'Expression Evaluation',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'stk_10',
    dataStructure: 'Stack',
    name: 'Decode String',
    link: 'https://leetcode.com/problems/decode-string/',
    pattern: 'Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_11',
    dataStructure: 'Stack',
    name: 'Trapping Rain Water',
    link: 'https://leetcode.com/problems/trapping-rain-water/',
    pattern: 'Monotonic Stack',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'stk_12',
    dataStructure: 'Stack',
    name: 'Remove K Digits',
    link: 'https://leetcode.com/problems/remove-k-digits/',
    pattern: 'Monotonic Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_13',
    dataStructure: 'Stack',
    name: 'Simplify Path',
    link: 'https://leetcode.com/problems/simplify-path/',
    pattern: 'Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_14',
    dataStructure: 'Stack',
    name: 'Removing Stars From a String',
    link: 'https://leetcode.com/problems/removing-stars-from-a-string/',
    pattern: 'Stack',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'stk_15',
    dataStructure: 'Stack',
    name: 'Baseball Game',
    link: 'https://leetcode.com/problems/baseball-game/',
    pattern: 'Stack',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'stk_16',
    dataStructure: 'Stack',
    name: 'Asteroid Collision',
    link: 'https://leetcode.com/problems/asteroid-collision/',
    pattern: 'Monotonic Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_17',
    dataStructure: 'Stack',
    name: 'Final Prices With Discount',
    link: 'https://leetcode.com/problems/final-prices-with-a-special-discount-in-a-shop/',
    pattern: 'Monotonic Stack',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'stk_18',
    dataStructure: 'Stack',
    name: 'Sum of Subarray Minimums',
    link: 'https://leetcode.com/problems/sum-of-subarray-minimums/',
    pattern: 'Monotonic Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_19',
    dataStructure: 'Stack',
    name: 'Maximum Score from Removing Substrings',
    link: 'https://leetcode.com/problems/maximum-score-from-removing-substrings/',
    pattern: 'Stack',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'stk_20',
    dataStructure: 'Stack',
    name: 'Number of Atoms',
    link: 'https://leetcode.com/problems/number-of-atoms/',
    pattern: 'Stack',
    difficulty: 'Hard',
    completed: false,
  },

  // QUEUE/DEQUE - 15 problems
  {
    id: 'q_1',
    dataStructure: 'Queue/Deque',
    name: 'Number of Islands',
    link: 'https://leetcode.com/problems/number-of-islands/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_2',
    dataStructure: 'Queue/Deque',
    name: 'Binary Tree Level Order Traversal',
    link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_3',
    dataStructure: 'Queue/Deque',
    name: 'Sliding Window Maximum',
    link: 'https://leetcode.com/problems/sliding-window-maximum/',
    pattern: 'Monotonic Queue',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'q_4',
    dataStructure: 'Queue/Deque',
    name: 'Walls and Gates',
    link: 'https://leetcode.com/problems/walls-and-gates/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_5',
    dataStructure: 'Queue/Deque',
    name: 'Shortest Distance in Grid',
    link: 'https://leetcode.com/problems/shortest-distance-from-all-buildings/',
    pattern: 'BFS',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'q_6',
    dataStructure: 'Queue/Deque',
    name: 'Rotten Oranges',
    link: 'https://leetcode.com/problems/rotting-oranges/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_7',
    dataStructure: 'Queue/Deque',
    name: 'Perfect Squares',
    link: 'https://leetcode.com/problems/perfect-squares/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_8',
    dataStructure: 'Queue/Deque',
    name: 'Maximum Frequency Stack',
    link: 'https://leetcode.com/problems/maximum-frequency-stack/',
    pattern: 'Priority Queue',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'q_9',
    dataStructure: 'Queue/Deque',
    name: 'Task Scheduler',
    link: 'https://leetcode.com/problems/task-scheduler/',
    pattern: 'Priority Queue',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_10',
    dataStructure: 'Queue/Deque',
    name: 'Top K Frequent Elements',
    link: 'https://leetcode.com/problems/top-k-frequent-elements/',
    pattern: 'Priority Queue',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_11',
    dataStructure: 'Queue/Deque',
    name: 'Implement Queue using Stacks',
    link: 'https://leetcode.com/problems/implement-queue-using-stacks/',
    pattern: 'Queue',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'q_12',
    dataStructure: 'Queue/Deque',
    name: 'Implement Deque',
    link: 'https://leetcode.com/problems/design-circular-deque/',
    pattern: 'Circular Queue',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_13',
    dataStructure: 'Queue/Deque',
    name: 'Kth Largest Element',
    link: 'https://leetcode.com/problems/find-the-kth-largest-element-in-an-array/',
    pattern: 'Priority Queue',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'q_14',
    dataStructure: 'Queue/Deque',
    name: 'Median Finder',
    link: 'https://leetcode.com/problems/find-median-from-data-stream/',
    pattern: 'Priority Queue',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'q_15',
    dataStructure: 'Queue/Deque',
    name: 'Connecting Cities With Minimum Cost',
    link: 'https://leetcode.com/problems/connecting-cities-with-minimum-cost/',
    pattern: 'BFS',
    difficulty: 'Hard',
    completed: false,
  },

  // TREES - 40 problems
  {
    id: 'tree_1',
    dataStructure: 'Trees',
    name: 'Binary Tree Inorder Traversal',
    link: 'https://leetcode.com/problems/binary-tree-inorder-traversal/',
    pattern: 'DFS',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_2',
    dataStructure: 'Trees',
    name: 'Binary Tree Preorder Traversal',
    link: 'https://leetcode.com/problems/binary-tree-preorder-traversal/',
    pattern: 'DFS',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_3',
    dataStructure: 'Trees',
    name: 'Binary Tree Postorder Traversal',
    link: 'https://leetcode.com/problems/binary-tree-postorder-traversal/',
    pattern: 'DFS',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_4',
    dataStructure: 'Trees',
    name: 'Binary Tree Level Order Traversal',
    link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_5',
    dataStructure: 'Trees',
    name: 'Symmetric Tree',
    link: 'https://leetcode.com/problems/symmetric-tree/',
    pattern: 'Recursion',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_6',
    dataStructure: 'Trees',
    name: 'Maximum Depth of Binary Tree',
    link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    pattern: 'DFS',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_7',
    dataStructure: 'Trees',
    name: 'Minimum Depth of Binary Tree',
    link: 'https://leetcode.com/problems/minimum-depth-of-binary-tree/',
    pattern: 'DFS',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_8',
    dataStructure: 'Trees',
    name: 'Validate Binary Search Tree',
    link: 'https://leetcode.com/problems/validate-binary-search-tree/',
    pattern: 'Binary Search Tree',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_9',
    dataStructure: 'Trees',
    name: 'Lowest Common Ancestor',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    pattern: 'LCA',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_10',
    dataStructure: 'Trees',
    name: 'Lowest Common Ancestor (Binary Tree)',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
    pattern: 'LCA',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_11',
    dataStructure: 'Trees',
    name: 'Binary Tree Diameter',
    link: 'https://leetcode.com/problems/diameter-of-binary-tree/',
    pattern: 'Diameter',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_12',
    dataStructure: 'Trees',
    name: 'Balanced Binary Tree',
    link: 'https://leetcode.com/problems/balanced-binary-tree/',
    pattern: 'Balanced Tree',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_13',
    dataStructure: 'Trees',
    name: 'Path Sum',
    link: 'https://leetcode.com/problems/path-sum/',
    pattern: 'Path Sum',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_14',
    dataStructure: 'Trees',
    name: 'Path Sum II',
    link: 'https://leetcode.com/problems/path-sum-ii/',
    pattern: 'Path Sum',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_15',
    dataStructure: 'Trees',
    name: 'Sum Root to Leaf Numbers',
    link: 'https://leetcode.com/problems/sum-root-to-leaf-numbers/',
    pattern: 'Path Sum',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_16',
    dataStructure: 'Trees',
    name: 'Serialize and Deserialize Binary Tree',
    link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
    pattern: 'Serialization',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_17',
    dataStructure: 'Trees',
    name: 'Construct Binary Tree from Preorder and Inorder',
    link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
    pattern: 'Recursion',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_18',
    dataStructure: 'Trees',
    name: 'Construct Binary Tree from Inorder and Postorder',
    link: 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/',
    pattern: 'Recursion',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_19',
    dataStructure: 'Trees',
    name: 'Vertical Order Traversal',
    link: 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/',
    pattern: 'BFS',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_20',
    dataStructure: 'Trees',
    name: 'Flatten Binary Tree to Linked List',
    link: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/',
    pattern: 'Traversal',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_21',
    dataStructure: 'Trees',
    name: 'Binary Search Tree Iterator',
    link: 'https://leetcode.com/problems/binary-search-tree-iterator/',
    pattern: 'Binary Search Tree',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_22',
    dataStructure: 'Trees',
    name: 'Kth Smallest Element in BST',
    link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
    pattern: 'Binary Search Tree',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_23',
    dataStructure: 'Trees',
    name: 'Inorder Successor in BST',
    link: 'https://leetcode.com/problems/inorder-successor-in-bst/',
    pattern: 'Binary Search Tree',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_24',
    dataStructure: 'Trees',
    name: 'LCA of BST',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    pattern: 'Binary Search Tree',
    difficulty: 'Easy',
    completed: false,
  },
  {
    id: 'tree_25',
    dataStructure: 'Trees',
    name: 'Binary Tree Right Side View',
    link: 'https://leetcode.com/problems/binary-tree-right-side-view/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_26',
    dataStructure: 'Trees',
    name: 'Populating Next Right Pointers',
    link: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/',
    pattern: 'BFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_27',
    dataStructure: 'Trees',
    name: 'Recover Binary Search Tree',
    link: 'https://leetcode.com/problems/recover-binary-search-tree/',
    pattern: 'Binary Search Tree',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_28',
    dataStructure: 'Trees',
    name: 'All Nodes Distance K in Binary Tree',
    link: 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/',
    pattern: 'DFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_29',
    dataStructure: 'Trees',
    name: 'Most Frequent Subtree Sum',
    link: 'https://leetcode.com/problems/most-frequent-subtree-sum/',
    pattern: 'DFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_30',
    dataStructure: 'Trees',
    name: 'Maximum Path Sum',
    link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    pattern: 'Path Sum',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_31',
    dataStructure: 'Trees',
    name: 'Implement Trie',
    link: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    pattern: 'Trie',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_32',
    dataStructure: 'Trees',
    name: 'Word Search II',
    link: 'https://leetcode.com/problems/word-search-ii/',
    pattern: 'Trie',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_33',
    dataStructure: 'Trees',
    name: 'Prefix and Suffix Search',
    link: 'https://leetcode.com/problems/prefix-and-suffix-search/',
    pattern: 'Trie',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_34',
    dataStructure: 'Trees',
    name: 'Replace Words',
    link: 'https://leetcode.com/problems/replace-words/',
    pattern: 'Trie',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_35',
    dataStructure: 'Trees',
    name: 'Longest Word in Dictionary',
    link: 'https://leetcode.com/problems/longest-word-in-dictionary/',
    pattern: 'Trie',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_36',
    dataStructure: 'Trees',
    name: 'Map Sum Pairs',
    link: 'https://leetcode.com/problems/map-sum-pairs/',
    pattern: 'Trie',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_37',
    dataStructure: 'Trees',
    name: 'House Robber III',
    link: 'https://leetcode.com/problems/house-robber-iii/',
    pattern: 'DFS',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_38',
    dataStructure: 'Trees',
    name: 'Unique Binary Search Trees',
    link: 'https://leetcode.com/problems/unique-binary-search-trees/',
    pattern: 'Binary Search Tree',
    difficulty: 'Medium',
    completed: false,
  },
  {
    id: 'tree_39',
    dataStructure: 'Trees',
    name: 'Binary Tree Cameras',
    link: 'https://leetcode.com/problems/binary-tree-cameras/',
    pattern: 'Greedy DFS',
    difficulty: 'Hard',
    completed: false,
  },
  {
    id: 'tree_40',
    dataStructure: 'Trees',
    name: 'Validate Binary Search Tree',
    link: 'https://leetcode.com/problems/validate-binary-search-tree/',
    pattern: 'Binary Search Tree',
    difficulty: 'Medium',
    completed: false,
  },
]

export default generateProblems
